### PR TITLE
Fix/grpc keepalive

### LINKED ISSUE #885: Feature: Make gRPC connections more robust
### Motivation

Currently, when there is a gRPC connection between services, and some network disturbance occurs, the connection will fail and the service will not retry to establish the connection again. This results in errors which could be prevented.

### Description

The issue aims to improve the robustness of the gRPC connections by adding retries and possibly something more.

### Exit criteria
- [ ] The gRPC connections are reasonably robust to handle minor network disruptions

### PR DESCRIPTION
**Pull request by Despire**
closes #885 

by setting the keepalive params for a client connection and adding a retry policy on RPC that fail due to code `unavailable` 

`Unavailable indicates the service is currently unavailable`

The client will try for roughly ~10 minutes for the service to become available and retry the RPC, given that our calls are idempotent this shouldn't be an issues.

It may happen that two calls at the same time will be executed (the one previosly started where the connection was lost and the new one), however. In terraformer we use a lock so that shouldn't be an issues and with the rest of the calls it shouldn't raise any negative side effects.

### CODE REVIEW

File: internal/utils/grpc.go [hunk 1]
```diff
@@ -16,10 +19,48 @@ func CloseClientConnection(connection *grpc.ClientConn) {
 }
 
 func GrpcDialWithInsecure(serviceName string, serviceURL string) (*grpc.ClientConn, error) {
-	cc, err := grpc.Dial(serviceURL, grpc.WithTransportCredentials(insecure.NewCredentials()))
+	kacp := keepalive.ClientParameters{
+		Time:                60 * time.Second, // ping the server every ~60 seconds.
+		Timeout:             20 * time.Minute, // wait up to 20 minutes for a packet to be acknowledged.
```
Comment (MiroslavRepka) [inline internal/utils/grpc.go:24]: Isn't this value a bit high?

File: internal/utils/grpc.go [hunk 2]
```diff
@@ -16,10 +19,48 @@ func CloseClientConnection(connection *grpc.ClientConn) {
...
+		PermitWithoutStream: true,             // send pings if there are no active streams (RPCs).
+	}
+
+	// retry policy for RPC calls.
+	opts := []grpc_retry.CallOption{
+		grpc_retry.WithBackoff(grpc_retry.BackoffLinearWithJitter(45*time.Second, 0.1)),
+		grpc_retry.WithMax(15),
```
Comment (MiroslavRepka) [inline internal/utils/grpc.go:49]: Ditto, arent 15 retries a bit too much?

File: internal/utils/grpc.go [hunk 3]
```diff
@@ -16,10 +19,48 @@ func CloseClientConnection(connection *grpc.ClientConn) {
 }
 
 func GrpcDialWithInsecure(serviceName string, serviceURL string) (*grpc.ClientConn, error) {
```
Comment (MiroslavRepka) [inline internal/utils/grpc.go:21]: Is this function even used anywhere now?

File: internal/utils/grpc.go (hunk 2 above)
Comment (Despire) [reply internal/utils/grpc.go:49]: 15 every 45 seconds is ~11 mins, which I think is okay-ish, we could half it to 6 minutes I would be okay either way

File: internal/utils/grpc.go (hunk 3 above)
Comment (Despire) [reply internal/utils/grpc.go:21]: In two `_test` files I can also replaced them there and remove this function

File: internal/utils/grpc.go (hunk 1 above)
Comment (Despire) [reply internal/utils/grpc.go:24]: It may be, we can halve it to 10 minutes, what number would you suggest ?

File: internal/utils/grpc.go (hunk 2 above)
Comment (MiroslavRepka) [reply internal/utils/grpc.go:49]: I would probably prefer to halve it if thats okay

File: internal/utils/grpc.go (hunk 3 above)
Comment (MiroslavRepka) [reply internal/utils/grpc.go:21]: Yeah, might as well replace it

File: internal/utils/grpc.go (hunk 1 above)
Comment (MiroslavRepka) [reply internal/utils/grpc.go:24]: [gRPC defaults](https://grpc.io/docs/guides/keepalive/#keepalive-configuration-specification) seems to be 20s for both client and server.
image

Comment (Despire) [reply internal/utils/grpc.go:24]: I think 20s is a bit low, I would set it to 5 mins.

Comment (MiroslavRepka) [reply internal/utils/grpc.go:24]: Sure, let's set it to 5min then

**Review by MiroslavRepka — COMMENTED** [review]
LGTM, thanks @Despire!

**Review by MiroslavRepka — APPROVED** [review]

**Review by cloudziu — APPROVED** [review]
Awesome! Thanks :D

**Comment by Despire** [comment]
Had to also adjust the server settings as otherwise the server would just sent 

`[transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".`

File: internal/utils/grpc.go [hunk 4]
```diff
@@ -18,6 +19,22 @@ func CloseClientConnection(connection *grpc.ClientConn) {
...
+		grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
+			MinTime:             45 * time.Second, // If a client pings more than once every 45 seconds, terminate the connection
+			PermitWithoutStream: true,             // Allow pings even when there are no active streams
+		}),
+		grpc.KeepaliveParams(keepalive.ServerParameters{
+			MaxConnectionIdle:     math.MaxInt64,   // If a client is idle for INFINITE seconds, send a GOAWAY.
+			MaxConnectionAge:      math.MaxInt64,   // If any connection is alive for more than INIFINITE seconds, send a GOAWAY.
+			MaxConnectionAgeGrace: math.MaxInt64,   // Allow INIFNITE seconds for pending RPCs to complete before forcibly closing connections.
+			Time:                  2 * time.Hour,   // Ping the client if it is idle for 2 Hours to ensure the connection is still active.
+			Timeout:               5 * time.Minute, // Wait 5 minutes for the ping ack before assuming the connection is dead.
```
Comment (cloudziu) [inline internal/utils/grpc.go:33]: I'm not sure about that. If a service isn't responding for 5min I wouldn't expect any answer at all. The default value is 20seconds here. Is there a reason why we want to elevate it to 5min?

**Review by cloudziu — APPROVED** [review]

**Review by MiroslavRepka — APPROVED** [review]
